### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by vnen**
Related to #5 

Couldn't make it work but I'm not used to QT and may be missing something. If you need I can change stuff to make it work properly.

### CODE REVIEW

**Comment by azagaya** [comment]
Hi! thanks a lot! I'm very happy to have your help!
The translation may have not worked on your computer, because currently i'm only looking for the language code, and not at the country code. For example, my locale is "es_AR", but im only keeping the "es" part, because spanish is almost the same everywhere (afaik). If there is not much difference between Brazilian Portuguese and just Portuguese, we could just rename your file like "laigter_pt". Or better, we should check first to load the full locale (e.g "pt_BR") and if that fails try with language code alone (e.g "pt") alone.
If you agree with that, the code that should be changed is in main file, lines 45-49:
```c++
  QString locale = QLocale::system().name().split("_").at(0);
  QTranslator translator;
  bool loaded = translator.load(":/laigter_" + locale);
  if (!loaded)
    translator.load(":/laigter_en");
```
I think we could first try to load the full locale (without split) and if it fails, try only with language (or load anyone with the same language regardless the country), and if it fails, load english. What do you think?

**Comment by vnen** [comment]
> The translation may have not worked on your computer, because currently i'm only looking for the language code, and not at the country code.

Ah, that makes sense.

> If there is not much difference between Brazilian Portuguese and just Portuguese, we could just rename your file like "laigter_pt"

One can understand the other, but there's enough difference in translation choices. Some words in `pt_BR` aren't used in `pt_PT` and vice-versa. I guess we could leave this as only `pt`, since there's no  `pt_PT` translation yet.

> Or better, we should check first to load the full locale (e.g "pt_BR") and if that fails try with language code alone (e.g "pt") alone.
>
> [...]
>
> I think we could first try to load the full locale (without split) and if it fails, try only with language (or load anyone with the same language regardless the country), and if it fails, load english. What do you think?

Yeah, for i18n purposes this approach is better.

I can to change this tonight and apply it to this PR if you want.

**Comment by azagaya** [comment]
That would be great yes!
Thanks! I'll wait for your PR update.

**Comment by vnen** [comment]
I discovered that QT already does the fallback automatically. I also changed it to use the recommend function as said in documentation: https://doc.qt.io/qt-5/qtranslator.html#load-1

**Comment by azagaya** [comment]
Thanks a lot!!

**Pull request merged**
