### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BlueManCZ**
It should be [hdf5](https://www.archlinux.org/packages/community/x86_64/hdf5/), right?

### CODE REVIEW

**Comment by azagaya** [comment]
You are right, but actually, as i removed opencv, i think hdf5 is not needed anymore.

**Comment by BlueManCZ** [comment]
Ok, I see.

I will ask here. Do you have any idea, what can cause `qt.qpa.backingstore: composeAndFlush: makeCurrent() failed` error? 
Snímek z 2020-07-22 17-34-59

**Comment by azagaya** [comment]
Can you check your opengl library version, and supported version by your GPU?

**Comment by BlueManCZ** [comment]
It may be related to my currently running update. I think Nvidia drivers were included. I will try to restart as soon as possible.

**Comment by BlueManCZ** [comment]
All right. Works like a charm after reboot on my Gentoo. So I can confirm. No hdf5 nor vtk necessary for startup.

**Comment by azagaya** [comment]
Great! would you remove that dependencies from readme and update this PR? so i can merge it.

**Comment by BlueManCZ** [comment]
Sure

**Comment by azagaya** [comment]
Thanks!

**Pull request merged**
