### PR TITLE
Initial Japanese translation

### PR DESCRIPTION
**Pull request by kusogaki77**
Note: I expect there are some translations that won't sound natural.  I need to build the application and use it to see which are strange and fix them.

### CODE REVIEW

**Comment by azagaya** [comment]
hi @kusogaki77 
Sorry for the late response. Here you have a build for win64, portable, with japanese language. You just need to select the language from the flag icon in the toolbar.
Please let me know if it works!
https://mega.nz/file/z6wR0ZJY#8ggQ2g3b80c5eKOz9IFW3TM_6jyMiWj4OBKjUiD3I2U

**Comment by kusogaki77** [comment]
Hey, sorry for the late reply!
Thanks a lot for the offer!  My name is Hans Wakelin. If you add that
string I'll translate it, too, later.  I'll delete my current fork, and
re-fork the latest from your repo and then make sure there aren't any
outstanding strings that haven't been translated.

**Comment by azagaya** [comment]
@kusogaki77 hey! i've updated your name! you should see it in master branch. Thanks!

**Comment by kusogaki77** [comment]
Damn, you're too fast!  lol
Thank you!

Hmm, I didn't see any untranslated strings in the laigter_jp.ts file when I
just synced to master.
Could you tell me the original English/Spanish (save/load) strings that you
added or tell me which changelist contained the new strings?  I'm better
with SVN than github.

**Comment by azagaya** [comment]
sorry.. idk why qt didn't updated the ts file. check it now!

**Pull request merged**
