### PR TITLE
Fix build with opencv 4

### PR DESCRIPTION
**Pull request by david-geiger**

### CODE REVIEW

**Comment by azagaya** [comment]
Hi! thanks for the contribution. I have one question. I'm able to build with opencv4 without that include. Is the build failing for you without it? on which platform? 
Thanks!

**Comment by david-geiger** [comment]
Yes without that change we have encountered a build error (I don't remember which exactly) but on our distro Mageia Linux (64, 32, armv7 and aarch64) it build successfully now with opencv 4.2.0.

**Comment by azagaya** [comment]
Ok, i'll merge it then! 
Thanks!

**Comment by david-geiger** [comment]
ah ok found the exact build issue it was:

> g++ -c -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -fno-strict-aliasing -DPIC -fPIC -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/opencv4/opencv2 -isystem /usr/include/opencv4 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o imageprocessor.o src/imageprocessor.cpp
src/imageprocessor.cpp: In member function 'void ImageProcessor::set_current_heightmap()':
src/imageprocessor.cpp:170:43: error: 'CV_RGBA2GRAY' was not declared in this scope
  170 |   cvtColor(current_heightmap, m_parallax, CV_RGBA2GRAY);
      |                                           ^~~~~~~~~~~~
src/imageprocessor.cpp: In member function 'int ImageProcessor::set_neighbour_image(QString, QImage, int, int)':
src/imageprocessor.cpp:315:49: warning: unused parameter 'fileName' [-Wunused-parameter]
  315 | int ImageProcessor::set_neighbour_image(QString fileName, QImage image, int x,
      |                                         ~~~~~~~~^~~~~~~~
src/imageprocessor.cpp: In member function 'void ImageProcessor::calculate_distance()':
src/imageprocessor.cpp:502:45: error: 'CV_DIST_L2' was not declared in this scope
  502 |   distanceTransform(m_distance, m_distance, CV_DIST_L2, 5);
      |                                             ^~~~~~~~~~
src/imageprocessor.cpp: In member function 'cv::Mat ImageProcessor::modify_occlusion()':
src/imageprocessor.cpp:584:29: error: 'CV_DIST_L2' was not declared in this scope
  584 |     distanceTransform(m, m, CV_DIST_L2, 5);
      |                             ^~~~~~~~~~
src/imageprocessor.cpp:611:18: error: 'CV_GRAY2RGB' was not declared in this scope
  611 |   m.convertTo(m, CV_GRAY2RGB, 1);
      |                  ^~~~~~~~~~~
src/imageprocessor.cpp: In member function 'cv::Mat ImageProcessor::modify_parallax()':
src/imageprocessor.cpp:640:20: error: 'CV_RGBA2GRAY' was not declared in this scope
  640 |     cvtColor(m, m, CV_RGBA2GRAY);
      |                    ^~~~~~~~~~~~
src/imageprocessor.cpp: In member function 'cv::Mat ImageProcessor::modify_specular()':
src/imageprocessor.cpp:679:18: error: 'CV_RGBA2GRAY' was not declared in this scope
  679 |   cvtColor(m, m, CV_RGBA2GRAY);
      |                  ^~~~~~~~~~~~
src/imageprocessor.cpp: In member function 'void ImageProcessor::copy_settings(ProcessorSettings)':
src/imageprocessor.cpp:768:70: warning: implicitly-declared 'constexpr ProcessorSettings::ProcessorSettings(const ProcessorSettings&)' is deprecated [-Wdeprecated-copy]
  768 | void ImageProcessor::copy_settings(ProcessorSettings s) { settings = s; }
      |                                                                      ^
In file included from src/imageprocessor.cpp:20:
src/imageprocessor.h:47:22: note: because 'ProcessorSettings' has user-provided 'ProcessorSettings& ProcessorSettings::operator=(ProcessorSettings)'
   47 |   ProcessorSettings &operator=(ProcessorSettings other);
      |                      ^~~~~~~~
src/imageprocessor.h:47:50: note:   initializing argument 1 of 'ProcessorSettings& ProcessorSettings::operator=(ProcessorSettings)'
   47 |   ProcessorSettings &operator=(ProcessorSettings other);
      |                                ~~~~~~~~~~~~~~~~~~^~~~~
src/imageprocessor.cpp: In member function 'ProcessorSettings ImageProcessor::get_settings()':
src/imageprocessor.cpp:770:59: warning: implicitly-declared 'constexpr ProcessorSettings::ProcessorSettings(const ProcessorSettings&)' is deprecated [-Wdeprecated-copy]
  770 | ProcessorSettings ImageProcessor::get_settings() { return settings; }
      |                                                           ^~~~~~~~
In file included from src/imageprocessor.cpp:20:
src/imageprocessor.h:47:22: note: because 'ProcessorSettings' has user-provided 'ProcessorSettings& ProcessorSettings::operator=(ProcessorSettings)'
   47 |   ProcessorSettings &operator=(ProcessorSettings other);
      |                      ^~~~~~~~
src/imageprocessor.cpp: In member function 'QImage ImageProcessor::get_heightmap()':
src/imageprocessor.cpp:1013:34: error: 'CV_RGBA2GRAY' was not declared in this scope
 1013 |   cvtColor(current_heightmap, m, CV_RGBA2GRAY);
      |                                  ^~~~~~~~~~~~
src/imageprocessor.cpp:1014:18: error: 'CV_GRAY2RGB' was not declared in this scope
 1014 |   cvtColor(m, m, CV_GRAY2RGB);
      |                  ^~~~~~~~~~~
src/imageprocessor.cpp: In member function 'QImage ImageProcessor::get_distance_map()':
src/imageprocessor.cpp:1024:29: error: 'CV_GRAY2RGBA' was not declared in this scope
 1024 |   cvtColor(new_distance, m, CV_GRAY2RGBA);
      |                             ^~~~~~~~~~~~
make: *** [Makefile:588: imageprocessor.o] Error 1
make: *** Waiting for unfinished jobs....

**Pull request merged**
