### PR TITLE
preliminary file on change reloading

### PR DESCRIPTION
**Pull request by flamendless**

### CODE REVIEW

**Comment by azagaya** [comment]
Hi! Thanks a lot for your work. Some comments about it, mostly caused because you couldn't try as the shaders were broken:
In the line you do:
```cpp
if (file_path.compare(ip->get_name()))
```
It should be:
```cpp
if (!file_path.compare(ip->get_name()))
```
as compare results in 0 when both strings are equal. You could also use:
```cpp
if (file_path.compare == ip->get_name())
```
Which imo is more readable.
The line:
```cpp
QStringList directoryList = fs_watcher.directories();
```
Doesn't appear to be used. Was it a test? it may be deleted.

Some systems (as mine), when changing a file, they delete it and then write it again. This is a problem because QFileSystemWatcher removes from the list files that are deleted. This can be addressed adding something like this:

```cpp
if (!fs_watcher.files().contains(file_path)){
        fs_watcher.addPath(file_path);
}
```
The following line is not needed... it's just needed when opening a new texture and we want to set the same settings than the last opened one:
```cpp
ip->copy_settings(processor->get_settings());
```
And lastly, in the message box, i think its better to say "Image was modified" instead of "is modified". And also, remember to surround the messages with `tr()` so they are interpreted by Linguist when i'm doing translations. Something like this:

```cpp
QMessageBox::information(this, tr("File Modified"), tr("Your file was modified"));
```
If you need further help with this changes, please tell me! Or if you prefer me to do this changes, i can merge it as is, and then apply the fixes. And thanks a lot for your contribution.

**Comment by azagaya** [comment]
Also, shaders should work now in older glsl.. maybe you can try if it works now in your pc.

**Comment by azagaya** [comment]
Thanks a lot!

**Comment by azagaya** [comment]
Fixes #8

**Comment by flamendless** [comment]
Sure thing!

**Pull request merged**
