### PR TITLE
Create laigter_ca_ES.ts

### PR DESCRIPTION
**Pull request by hiulit**
Hi there!

Here are the translations for Catalan. I ended up using Qt Linguist so I guess everything should work.

Is there a way to test it myself? How can I compile Laigter for macOS? And how can I set the language to Catalan??

### CODE REVIEW

**Comment by hiulit** [comment]
Also, I've seen that there are a couple of things that are not translatable yet.

## Translations:
George Marques (vnen) - Brazilian Portuguese
Xavier Gómez (hiulit) - Catalan

I should include myself here, right? :P

## Programmers
George Marques (vnen) - Translation load

## Contributions
Lodugh (Participant!)

**Comment by azagaya** [comment]
Hi! First of all, thanks a lot for contributing!

> How can I compile Laigter for macOS?

In the readme there is a section for compiling in mac. You should check it ant if something doesn't work, ask us on discord.

> Also, I've seen that there are a couple of things that are not translatable yet.

Yes, those new text weren't generated yet. I don't think its too important to translate them.

> I should include myself here, right? :P

Of course!

**Comment by hiulit** [comment]
So will you create the new `<message>` for the new translators? Or can I create them myself?

**Comment by azagaya** [comment]
@hiulit you can create them yourself with lupdate (a cli tool for generating the translations that comes with Qt).

**Comment by azagaya** [comment]
Thanks!

**Pull request merged**
