### PR TITLE
Add Simplified Chinese translation.

### PR DESCRIPTION
**Pull request by SakuraNeko**
Simplified Chinese localization work was performed, but no code quality check was performed.

eg. I am very sorry for the long delay of the promised translation.

### CODE REVIEW

**Comment by azagaya** [comment]
Hi! Im on holyday, so ill check this out when im back! Thanks a lot for contributing!

**Comment by azagaya** [comment]
Thanks! Ill make this available as binary soon!

**Comment by IceinNorth** [comment]
I would like to ask about the Chinese translation, I selected Chinese in Language, but it does not work, the interface is still in English

**Comment by azagaya** [comment]
@IceinNorth there is a fix in, but i need to fix other stuff before making a release..
You can get the binaries from the artifacts for now: https://github.com/azagaya/laigter/actions/runs/11278849039/artifacts/2041594391 (says mac-artifact but is windows).

Sorry for the delay, my day jobs is taking all my free time.

**Pull request merged**
